### ISSUE TITLE
Speed test

### ISSUE THREAD

**Issue by farizrahman4u** [titu1994/keras-SRU#1]
Hey, can you do speed comparisons for [RS SRU implementation](http://www.github.com/farizrahman4u/keras-sru) against LSTM and CNN?

**Comment by titu1994** [comment]
I have to use my GPU for another project. The speed test is on IMDB dataset with batchsize 128. Would you be able to run it?

**Comment by titu1994** [comment]
Also, incredible that SRU can be written that easily in RecurrentShop.
