### ISSUE TITLE
Broken with keras 2.0.9

### ISSUE THREAD

**Issue by lminer** [titu1994/keras-SRU#5]
Looks like `from keras.layers.recurrent import _time_distributed_dense` no longer works with the big RNN refactor in 2.0.9.

**Comment by titu1994** [comment]
Yup thought as much. I'll update in a few hours.

**Comment by titu1994** [comment]
Should be fixed now.

**Comment by lminer** [comment]
Wow! Such speed!

**Comment by titu1994** [comment]
Haha, I have other repos with similar fixes so it's fast.
